config/routes.rb
Life::Application.routes.draw do

   root 'home#landing'
   
   
   
  resources :snapshots do
       member do
        post 'calendar_phantomjs'
      end
  end
  
  resources :snapshot_uploads do
       member do
        post 'wkhtmltopdf'
      end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def landing
    
  end
  
  
end

app/controllers/snapshot_uploads_controller.rb
class SnapshotUploadsController < ApplicationController

  def wkhtmltopdf
    file_name = params[:file]
    
    
    s3 = AWS::S3.new
   # args = "--page-height 279 --page-width 210 -O landscape -B 0mm -L 3mm -R 10mm -T 8mm -d 300"
    
    args = params["args"]
# Upload a file.  
    key = File.basename("test.html")        
    bucket_name = "danrailstest"
    s3.buckets[bucket_name].objects[key].write(:file => file_name, :acl=>:public_read)
    
    url = "http://s3.amazonaws.com/danrailstest/test.html"
    
  # wkhtmltopdf-012 --page-height 279 --page-width 210 -O landscape -B 0mm -L 3mm -R 10mm -T 8mm -d 300 http://127.0.0.1:3000/timeline small.pdf
     output_path = "#{Dir::tmpdir}/#{NumberHelper.get_random_code(5)}.pdf"
   
    command = "wkhtmltopdf-012  #{url} #{output_path}"
    
    logger.debug "command being run '#{command}'"
    
    #generate file 
    output = `#{command}`
    
    logger.debug "**command run"
    logger.debug "output: #{output}"
    
    #pdf jam
  
    
    
    #check if file exists
    
     if File.exists? output_path
       
     send_file output_path, :type => 'application/pdf', :filename =>"file.pdf", :disposition=>"attachment"
     
     else
       flash.alert = "That file could not be generated"
       redirect_to snapshot_uploads_path
       
    end
 end
      
end

app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController
  
  def calendar_phantomjs
    url = params[:url]
    
#     phantomjs-197 --ignore-ssl-errors=yes util/disney/rasterize.js http://127.0.0.1:3000/timeline test.pdf 1000 1000 1

    if url.blank?
      flash.alert = "Please enter a url"
      redirect_to snapshots_path 
      return
    end
    
    command_path = "#{Rails.root.to_s}/lib/rasterize.js "
    
    
    output_path = "#{Dir::tmpdir}/#{NumberHelper.get_random_code(5)}.pdf"
    width=params[:width]
    height=params[:height]
    zoom=1
    
    #width = "300"
    #height = "400"
    
    zoom = "1"
    command = "phantomjs-197 --ignore-ssl-errors=yes  #{command_path} #{url} #{output_path} #{width} #{height} #{zoom}"
    logger.debug "command being run '#{command}'"
    
    #generate file 
    output = `#{command}`
    
    logger.debug "**command run"
    logger.debug "output: #{output}"
    
    #pdf jam
  
    
    
    #check if file exists
    if File.exists? output_path
       
     send_file output_path, :type => 'application/pdf', :filename =>"file.pdf", :disposition=>"attachment"
     
     else
       flash.alert = "That file could not be generated"
       redirect_to snapshots_path
       
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/snapshot_uploads_helper.rb
module SnapshotUploadsHelper
end

app/helpers/snapshots_helper.rb
module SnapshotsHelper
end

app/views/home/landing.html.erb
hello.

<h1>Snapshots</h1>

<%=link_to "snapshots", snapshots_path%>

<%=link_to "upload snapshots", snapshot_uploads_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Life</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%if notice %> 
					<div class="alert alert-success">
			  		<button class="close" data-dismiss="alert">×</button>
	<%=notice %>
</div>
	
<%end%>
 	
<%if alert %> 
<div class="alert alert-error">
	<button class="close" data-dismiss="alert">×</button>
	<%=raw( alert) %>
</div>
<%end%>

<%= yield %>

</body>
</html>

app/views/snapshot_uploads/index.html.erb
<h1>Snapshots</h1>

Upload your file and click submit
<br><br>

<%= form_tag( wkhtmltopdf_snapshot_upload_path(1), :multipart=>true ) do %>
  <%= label_tag(:file, "File:") %>
  <%= file_field_tag( :file) %><br>
  <br>
  <br>
	 <%= label_tag(:args, "args") %>
  <%= text_field_tag(:args, "-page-size A4", :size=>150 )%>
  
  <br>
  <%= submit_tag("Submit") %>
<% end %>

<br><br>
--page-height 279 --page-width 210 -O landscape -B 0mm -L 3mm -R 10mm -T 8mm -d 300
<br>
-page-size A4

app/views/snapshots/index.html.erb
<h1>Snapshots</h1>

My JsFiddle URL : http://jsfiddle.net/palidanx/pYMjB/embedded/result/
<br>

Example of something that prints well: My JsFiddle URL : http://arshaw.com/js/fullcalendar-1.6.4/demos/agenda-views.html

<br><br>

<%= form_tag( calendar_phantomjs_snapshot_path(1) ) do %>
  <%= label_tag(:url, "URL:") %>
  <%= text_field_tag( :url, '', :size=>150) %>
  
  
  <br>
  <br>
  <br>
  <%= label_tag(:args, "width") %>
  <%= text_field_tag(:width, 2000) %>
  <br>
  <%= label_tag(:height, "height") %>
  <%= text_field_tag(:height, 1700) %>
  <br>
  <%= submit_tag("Submit") %>
<% end %>